project_id = "oviywityvklmftjxrnrj"

[functions.verify-captcha]
verify_jwt = false

[functions.public-config]
verify_jwt = false

[functions.analyze-reviews]
verify_jwt = false

[functions.upload-review-photo]
verify_jwt = false

[functions.customer-chat]
verify_jwt = false

[functions.check-replies]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true