
INSERT INTO public.reviews (name, email, rating, feedback, sentiment, approved, created_at) VALUES
('Alma Rivera', 'alma.r@email.com', 5, 'The ranch pizza is surprisingly good! Creamy ranch base with chicken, bacon, and onions. So unique!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Benito Santos', 'benito.s@email.com', 4, 'Solid takeout experience. Everything was packed well and tasted fresh when we got home.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Cecilia Torres', 'cecilia.t@email.com', 5, 'The staff singing happy birthday for my son was so sweet! The chocolate pizza was a hit with the kids.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Dario Reyes', 'dario.r@email.com', 5, 'Incredible flavor in the sausage and pepper pizza. Authentic Italian taste. Transport me to Naples!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Elena Mendoza', 'elena.m@email.com', 4, 'Nice clean dining area with good air conditioning. Pizza was hot and tasty. Reasonable prices.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Felix Garcia', 'felix.g@email.com', 5, 'The double pepperoni with extra cheese is my guilty pleasure. So good. No regrets.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Gloria Bautista', 'gloria.b@email.com', 4, 'Good atmosphere for a business lunch. Not too loud, good food, efficient service.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Hugo Fernandez', 'hugo.f@email.com', 5, 'The tomato soup paired with garlic breadsticks is perfection on a rainy day. Comfort food at its best!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Irene Lim', 'irene.l@email.com', 5, 'We had our engagement dinner here and it was magical. The food, service, and ambiance were all perfect.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Javier Aquino', 'javier.a@email.com', 4, 'The chicken alfredo pizza is unique and delicious. Creamy sauce with tender chicken on crispy crust.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Kristine Villanueva', 'kristine.v@email.com', 5, 'My picky eater son actually loves the pizza here! That says a lot. The cheese blend is really good.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Leandro Dela Cruz', 'leandro.dc@email.com', 5, 'Been going here since they opened and quality has only gotten better. The management clearly cares.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Maribel Tan', 'maribel.t@email.com', 4, 'The grilled chicken salad is massive and fresh! Great option when you want something lighter.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Nelson Gomez', 'nelson.g@email.com', 5, 'Pizza Volante catered my wedding rehearsal dinner and it was PERFECT. Guests are still talking about it.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Ophelia Ramos', 'ophelia.r@email.com', 4, 'Great weekend brunch option. The breakfast pizza with egg and bacon is creative and delicious.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Pedro Navarro', 'pedro.n@email.com', 5, 'Shout out to the delivery crew! Always on time, always friendly, always with a smile. Pizza is great too!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Queenie Ocampo Jr', 'queenie.oj@email.com', 4, 'The herb garden pizza with fresh rosemary and thyme is so fragrant. Love the creative toppings!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Rosa Castillo', 'rosa.c@email.com', 5, 'Every single time the food is consistent. That reliability is what makes Pizza Volante special.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Sergio Flores', 'sergio.f@email.com', 4, 'The loaded potato pizza is comfort food heaven. Crispy bacon, sour cream, chives on pizza dough. Genius!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Teresa Dizon', 'teresa.d@email.com', 5, 'Our office orders every payday and it never gets old. The variety keeps everyone happy.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Ulises Soriano', 'ulises.s@email.com', 5, 'The prosciutto and arugula pizza is restaurant quality. Fresh, peppery arugula on top of salty prosciutto. Divine!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Vanessa Evangelista', 'vanessa.e@email.com', 4, 'They have great gluten-free options! Finally a pizza place that takes dietary restrictions seriously.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Wilson Padilla', 'wilson.p@email.com', 5, 'The chili oil they put on the table is addictive! I put it on everything. The pizza itself is amazing too.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Xander Manalo', 'xander.m@email.com', 4, 'Good happy hour deals on drinks. The pizza pairs perfectly with their craft beer selection.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Yolinda Gutierrez', 'yolinda.g@email.com', 5, 'The artisan bread basket they serve before the meal is already better than most restaurant''s main dishes!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Zandro Salazar', 'zandro.s@email.com', 5, 'Impressed by how fresh everything tastes. Even the simple cheese pizza feels gourmet here.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Amanda Rivera', 'amanda.r@email.com', 4, 'Nice portion sizes. You definitely get your money''s worth here. The BBQ pizza was flavorful.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Blake Santos', 'blake.s@email.com', 5, 'My friends from abroad were blown away by the quality! They said Pizza Volante could easily compete internationally.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Celine Torres', 'celine.t@email.com', 4, 'The penne arrabbiata was perfectly spicy. Nice heat that builds slowly. Great pasta dish!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Derek Cruz', 'derek.c@email.com', 5, 'Love the open kitchen concept. Watching them toss the dough is entertaining! And the result is delicious.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),

-- More neutral reviews
('Elmer Reyes', 'elmer.r@email.com', 3, 'It was okay. The crust was a bit too crunchy for my preference. Sauce was decent though.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Fiona Mendoza', 'fiona.m@email.com', 3, 'Standard pizza. I''d rate it average among pizza places in the area. Nothing wrong but nothing special.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Gerardo Garcia', 'gerardo.g@email.com', 3, 'The food was fine. Not exciting but not bad. Just a regular Tuesday dinner.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Hannah Bautista', 'hannah.b@email.com', 3, 'Average experience. The wait was reasonable, food was acceptable, prices are normal.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Isidro Fernandez', 'isidro.f@email.com', 3, 'The Hawaiian pizza was standard. Pineapple and ham, nothing groundbreaking. It was an okay meal.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Josefina Lim', 'josefina.l@email.com', 3, 'Ordered online for pickup. Process was smooth. Pizza was ready on time. Taste was average.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Ken Aquino', 'ken.a@email.com', 3, 'The breadsticks are okay. Pizza is okay. Drinks are okay. Everything is just okay here.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Linda Villanueva', 'linda.v@email.com', 3, 'Not my first choice for pizza but it does the job when I''m in the neighborhood. Average quality.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Manny Dela Cruz', 'manny.dc@email.com', 3, 'It''s fine. Just fine. The pizza is neither great nor terrible. Middle of the pack.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Nora Tan', 'nora.t@email.com', 3, 'Had the veggie pizza. Vegetables were fresh but the overall taste was bland. Could use more seasoning.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),

-- More negative reviews
('Otto Gomez', 'otto.g@email.com', 2, 'The pepperoni was curled up and burnt. The cheese was rubbery. Not what I expected from the reviews.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Perla Ramos', 'perla.r@email.com', 1, 'Absolutely horrible service. Server spilled water on my lap and just walked away. Manager did nothing.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Quirino Navarro', 'quirino.n@email.com', 2, 'The delivery charge is outrageous and the pizza quality doesn''t justify it. Way overpriced for what you get.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Remedios Ocampo', 'remedios.o@email.com', 1, 'The restroom had no paper towels, no soap, and the toilet was broken. Hygiene is a serious concern here.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Santiago Castillo', 'santiago.c@email.com', 2, 'Ordered the supreme but got plain cheese. Called to complain and was put on hold for 20 minutes. Gave up.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Tessie Flores', 'tessie.f@email.com', 1, 'The food was cold, the staff was rude, and the bill was wrong. Trifecta of bad dining. Never again.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Ulysses Dizon', 'ulysses.d@email.com', 2, 'Used to be good but quality has really gone downhill recently. The dough tastes different and not in a good way.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Vilma Soriano', 'vilma.s@email.com', 1, 'Waited 45 minutes just for bread while watching tables that came after us get served first. No explanation given.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Werner Evangelista', 'werner.e@email.com', 2, 'The pizza was so thin it fell apart when I tried to pick up a slice. More like a cracker than pizza dough.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Ximena Padilla', 'ximena.p@email.com', 1, 'They forgot half our order and when we pointed it out they said we never ordered it. We showed them the receipt. Terrible.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Yasmin Manalo', 'yasmin.m@email.com', 2, 'The pizza sauce tasted like ketchup. That''s not pizza sauce. That''s laziness. Very unimpressed.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Zenon Gutierrez', 'zenon.g@email.com', 1, 'Order arrived missing items. Called customer service - no answer. Sent email - no reply. Zero accountability.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Aurora Salazar', 'aurora.s@email.com', 2, 'The chicken wings were so small and overcooked. Like eating chicken-flavored croutons. Waste of money.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Bong Rivera', 'bong.r@email.com', 1, 'Bit into a piece of plastic in my garlic bread. Almost choked. This place is a health hazard. Reporting them.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Corina Santos', 'corina.s@email.com', 2, 'The meatball sub was dry and the meatballs tasted like they came from a freezer bag. No homemade quality here.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Danilo Torres', 'danilo.t@email.com', 1, 'The pizza had barely any sauce. It was like eating cheese on bread. How is that even pizza? Total ripoff.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),

-- More positive to balance
('Elisa Cruz', 'elisa.c@email.com', 5, 'Date night at Pizza Volante is always a win! Great food, great company, great memories.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Fernando Reyes', 'fernando.r@email.com', 4, 'The grilled veggie pizza is so colorful and delicious. Zucchini, bell peppers, eggplant on a thin crust. Love it!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Gladys Mendoza', 'gladys.m@email.com', 5, 'I''ve tried pizza all over the country and Pizza Volante is easily in my top 3. The quality is remarkable.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Hector Garcia', 'hector.g@email.com', 5, 'The fresh basil on the margherita makes all the difference. You can tell they use quality ingredients.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Isabel Bautista', 'isabel.b@email.com', 4, 'Good WiFi, comfy seats, great pizza. Perfect spot to work remotely while enjoying amazing food.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Jorge Fernandez', 'jorge.f@email.com', 5, 'The chicken pesto wrap is the best thing on the secret menu! Ask for it - you won''t regret it.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Karen Lim', 'karen.l@email.com', 5, 'Pizza Volante is our go-to for every celebration. Birthdays, promotions, any excuse to eat great pizza!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Lorenzo Aquino', 'lorenzo.a@email.com', 4, 'The customer loyalty program is actually worth it. Got two free pizzas this month alone!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Mercedes Villanueva', 'mercedes.v@email.com', 5, 'From the first bite you know this is quality pizza. The dough, sauce, and cheese are all premium. Worth every peso!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Nicolas Dela Cruz', 'nicolas.dc@email.com', 4, 'Always a pleasure dining here. The staff is attentive without being intrusive. Food is consistently good.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Olivia Tan', 'olivia.t@email.com', 5, 'The cheese pull on their four cheese pizza should be in a commercial. So satisfying! Tastes as good as it looks.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Pablo Gomez', 'pablo.g@email.com', 5, 'Been a regular for 5 years. The only pizza place that has never let me down. Consistently excellent!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Rita Ramos Jr', 'rita.rj@email.com', 4, 'The tiramisu gelato is heavenly! Great dessert option after their already amazing pizza.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Stefan Navarro', 'stefan.n@email.com', 5, 'Pizza Volante has mastered the art of pizza making. Everything from the crust to the toppings is perfection.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Trina Ocampo', 'trina.o@email.com', 4, 'Love the seasonal specials! The summer mango pizza was unexpected but absolutely delicious.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Umberto Castillo Jr', 'umberto.cj@email.com', 5, 'Best late-night food spot! Open until midnight and the quality at 11:30pm is still top-notch.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Victoria Flores', 'victoria.f@email.com', 4, 'The fresh squeezed orange juice pairs so well with their breakfast pizza. Perfect morning combo!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Wendell Dizon', 'wendell.d@email.com', 5, 'Every family reunion we order from Pizza Volante. 30 people, never a single complaint. That''s quality!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Xena Soriano Jr', 'xena.sj@email.com', 5, 'The cheese they use is clearly imported. Rich, creamy, and melts perfectly. Worth the premium price.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Yael Evangelista', 'yael.e@email.com', 4, 'Great for group dinners. The sharing platters are generous and there''s something for everyone on the menu.', 'positive', true, now() - interval '1 day' * floor(random() * 90));
