
INSERT INTO public.reviews (name, email, rating, feedback, sentiment, approved, created_at) VALUES
-- Positive reviews 101-150
('Manny Pacquiao Jr', 'manny.pj@email.com', 5, 'The best pizza in the province! Every bite is full of flavor. The sauce is tangy and sweet, just perfect.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Cristina Aguilar', 'cristina.a@email.com', 5, 'My whole family loves Pizza Volante. We order every Friday night. The Hawaiian pizza is our favorite!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Paolo Avelino', 'paolo.a@email.com', 4, 'Great tasting pasta and the garlic bread is the best. Staff is always smiling.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Janine Gutierrez', 'janine.g@email.com', 5, 'The veggie supreme pizza is incredible! Fresh vegetables, flavorful sauce, and the crust is amazing.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Carlo Mendoza', 'carlo.m@email.com', 4, 'Good value for money. The lunch special with pizza and soup is perfect for a quick meal.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Maricel Soriano', 'maricel.s@email.com', 5, 'I always recommend Pizza Volante to friends visiting from out of town. Never received a single complaint!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Rico Blanco', 'rico.b@email.com', 5, 'The wood-fired taste really sets this apart. You can taste the smokiness in every slice. Authentic!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Liza Soberano', 'liza.s@email.com', 4, 'Love the new seasonal menu! The pesto chicken pizza was so creative and delicious.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Derek Ramsay', 'derek.r@email.com', 5, 'Incredible fried chicken! Juicy, flavorful, and the breading is perfectly seasoned. Better than the big chains.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Angel Locsin', 'angel.l@email.com', 5, 'Pizza Volante has the most generous toppings! Other places skimp but here you get your money''s worth.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Piolo Pascual', 'piolo.p@email.com', 4, 'Nice ambiance for a casual dinner. The lighting is warm and the music is not too loud. Food is great too.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Sarah Geronimo', 'sarah.g@email.com', 5, 'The cheese pizza here is simple perfection. My kids can''t get enough of it! Family-friendly place.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Gerald Anderson', 'gerald.a@email.com', 4, 'Quick service, hot food, fair prices. Everything a pizza place should be.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Kathryn Bernardo', 'kathryn.b@email.com', 5, 'Ordered for a party of 20 and everything was perfect! All pizzas arrived hot and on time. Amazing coordination!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Daniel Padilla', 'daniel.p@email.com', 4, 'The buffalo chicken pizza is fire! Spicy, tangy, and so satisfying. Goes great with their house lemonade.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Julia Barretto', 'julia.b@email.com', 5, 'Cleanest pizza place I''ve been to. You can see the kitchen from the dining area and it''s spotless!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Joshua Garcia', 'joshua.g@email.com', 4, 'The spaghetti bolognese is really rich and meaty. Generous portion too. Will definitely reorder.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Maine Mendoza', 'maine.m@email.com', 5, 'Everything is so instagrammable here! The food presentation is beautiful and it tastes even better than it looks.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Alden Richards', 'alden.r@email.com', 5, 'Best customer service I''ve experienced in a restaurant. They even remembered my name from last visit!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Nadine Lustre', 'nadine.l@email.com', 4, 'The truffle fries as a side with pizza? Chef''s kiss! Such a great combo. Highly recommend.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('James Reid', 'james.reid@email.com', 5, 'Pizza Volante is the GOAT. No other pizza place even comes close. The crust, sauce, cheese - perfection.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Bea Alonzo', 'bea.a@email.com', 4, 'Nice date night spot. The dim lighting and cozy booths create a romantic atmosphere. Food was excellent.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('John Lloyd Cruz', 'johnlloyd.c@email.com', 5, 'The quattro formaggi pizza is out of this world! Four cheeses blending together in harmony. Pure bliss.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Marian Rivera', 'marian.r@email.com', 5, 'We hosted our kid''s birthday party here and the staff was absolutely wonderful. They decorated the table and served the kids first. So thoughtful!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Dingdong Dantes', 'dingdong.d@email.com', 4, 'Reliable delivery service. Always on time, always hot, always correct order. Keep it up!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
-- Positive reviews 151-175
('Enchong Dee', 'enchong.d@email.com', 5, 'The prosciutto pizza is restaurant-quality at fast food prices. Can''t beat that value!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Erich Gonzales', 'erich.g@email.com', 4, 'Lovely brunch here. The breakfast pizza with eggs and bacon is a must-try!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Enrique Gil', 'enrique.g@email.com', 5, 'The fried chicken sandwich is amazing. Crispy chicken, fresh lettuce, special sauce. My new go-to!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Kim Chiu', 'kim.c@email.com', 5, 'Always consistent! Whether dine-in or delivery, the quality never changes. That''s what I love about Pizza Volante.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Xian Lim', 'xian.l@email.com', 4, 'The spinach and ricotta pizza is surprisingly good. Light and flavorful. Great option for something different.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Maja Salvador', 'maja.s@email.com', 5, 'The fresh fruit shakes are a game changer! Mango shake with pizza is the perfect combo.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Matteo Guidicelli', 'matteo.g@email.com', 4, 'Post-workout meal here hits different. Good protein options and the portions are satisfying.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Toni Gonzaga', 'toni.g@email.com', 5, 'Pizza Volante catered our company event and it was a huge hit! Everyone was asking where the food was from.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Paul Soriano', 'paul.s@email.com', 4, 'The weekend brunch deals are fantastic. Great food at great prices. The mimosas are a nice touch too.', 'positive', true, now() - interval '1 day' * floor(random() * 60)),
('Alex Gonzaga', 'alex.g@email.com', 5, 'Their online ordering system is so smooth! Easy to customize and the order was perfect. Tech-savvy pizza place!', 'positive', true, now() - interval '1 day' * floor(random() * 60)),

-- Neutral reviews 176-210
('Pedro Dominguez', 'pedro.d@email.com', 3, 'It was fine. Standard pizza. Nothing I''d post about on social media but nothing I''d complain about.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Carmen Electra', 'carmen.e@email.com', 3, 'The pizza was average. I expected more given the reviews I''d read online. Maybe I set my expectations too high.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Roberto Clemente', 'roberto.c@email.com', 3, 'Decent enough for a weeknight dinner. Not a destination restaurant but a good neighborhood pizza spot.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Elena Vasquez', 'elena.v@email.com', 3, 'The margherita was standard. Fresh basil was nice but the sauce could be more flavorful. Okay overall.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Hector Martinez', 'hector.m@email.com', 3, 'Went for lunch. Service was quick. Pizza was warm and had decent taste. A normal pizza experience.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Lucia Fernandez', 'lucia.f@email.com', 3, 'The fried chicken was average. Not bad but I''ve had better. The rice was good though.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Manuel Ortiz', 'manuel.o@email.com', 3, 'Okay place. Nothing stands out. Pizza is similar to what you''d get at most places in the area.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Rosario Santos', 'rosario.s@email.com', 3, 'The atmosphere is pleasant but the food is just average. The pasta could use more seasoning.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Emilio Aguinaldo', 'emilio.a@email.com', 3, 'Average pizza. Crust was okay, toppings were okay, price was okay. Everything was just okay.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Aurora Reyes', 'aurora.r@email.com', 3, 'Had the family meal. Kids ate without complaints but my wife and I thought the flavors were muted.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Gregorio Araneta', 'gregorio.a@email.com', 3, 'Standard fare. The pizza is serviceable. Not going to blow your mind but gets the job done.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Dolores Hidalgo', 'dolores.h@email.com', 3, 'It''s a pizza place. Does what it says. Nothing more, nothing less. Adequate food and service.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Ramon Magsaysay', 'ramon.m@email.com', 3, 'The menu is extensive but nothing really wowed me. Each item was decent but unremarkable.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Imelda Marcos Jr', 'imelda.mj@email.com', 3, 'Clean restaurant, polite staff, average food. It''s fine for what it is.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),
('Jose Rizal', 'jose.r@email.com', 3, 'The pizza had a nice crust but the toppings were sparse. For the price, I expected more generous portions.', 'neutral', true, now() - interval '1 day' * floor(random() * 60)),

-- Negative reviews 211-250
('Fernando Poe', 'fernando.p@email.com', 1, 'Absolutely the worst dining experience. Cold food, rude waiter, and they overcharged us. Never again.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Miriam Defensor', 'miriam.d@email.com', 2, 'The pizza was burnt on the edges and raw in the middle. How do you mess that up? Unacceptable.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Corazon Santiago', 'corazon.s@email.com', 1, 'The restroom was filthy and there was no soap. If they can''t keep the bathroom clean, imagine the kitchen.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Fidel Ramos', 'fidel.r@email.com', 2, 'Overpriced and underwhelming. The fried chicken was tiny and the sides were pathetic. Such a letdown.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Gloria Arroyo', 'gloria.ar@email.com', 1, 'We waited 50 minutes for TWO pizzas. When they arrived, one was wrong. Staff didn''t care. Horrible.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Rodrigo Roa', 'rodrigo.r@email.com', 2, 'The air conditioning was broken. Eating hot pizza in a sweltering restaurant is not a pleasant experience.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Benigno Simeon', 'benigno.s@email.com', 1, 'Cockroach crawling on the wall next to our table. We left immediately. Disgusting and unsanitary.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Joseph Estrada', 'joseph.e@email.com', 2, 'The delivery driver was 40 minutes late and didn''t even apologize. Pizza was stone cold.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Manuel Quezon', 'manuel.q@email.com', 1, 'The spaghetti tasted like cafeteria food. Watery sauce, mushy noodles, and barely any meat. Terrible.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Sergio Osmena', 'sergio.o@email.com', 2, 'Stale bread and the dipping sauce had an off taste. Not what I expected from the online reviews.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Elpidio Quirino', 'elpidio.q@email.com', 1, 'They charged me for items I didn''t order and the manager refused to fix the bill. Dishonest practices.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Carlos Garcia Jr', 'carlos.gj@email.com', 2, 'The toppings were not fresh. The vegetables looked like they''d been sitting out all day. Very disappointing.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Diosdado Macapagal', 'diosdado.m@email.com', 1, 'Found a plastic piece in my fried chicken. Could have choked. This is dangerous and negligent.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Ferdinand Marcos', 'ferdinand.m@email.com', 2, 'The pizza box was soaked with grease. Disgusting presentation. The pizza itself was mediocre at best.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Emilio Jacinto', 'emilio.j@email.com', 1, 'The worst customer service ever. Staff was on their phones instead of taking orders. Had to yell to get attention.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Andres Bonifacio', 'andres.b@email.com', 2, 'Bland, tasteless pizza. Zero seasoning. Even the cheese tasted like nothing. Such a waste.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Apolinario Mabini', 'apolinario.m@email.com', 1, 'The online order system double charged my card. Took 2 weeks to get a refund. Terrible!', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Gabriela Silang', 'gabriela.s@email.com', 2, 'Portion sizes have shrunk drastically. Same price but way less food. Not worth it anymore.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Juan Luna', 'juan.l@email.com', 1, 'The pizza crust tasted stale. Like they used day-old dough. And the cheese was barely melted. Awful.', 'negative', true, now() - interval '1 day' * floor(random() * 60)),
('Lapu Lapu', 'lapu.l@email.com', 2, 'Super salty pizza. Like someone spilled the salt shaker on it. Had to drink 3 glasses of water. Terrible.', 'negative', true, now() - interval '1 day' * floor(random() * 60));
