
INSERT INTO public.reviews (name, email, rating, feedback, sentiment, approved, created_at) VALUES
-- Positive reviews 371-420
('Diana Morales', 'diana.m2@email.com', 5, 'The stuffed crust is a game changer! Cheese oozing from every bite. Pizza Volante does it right.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Edwin Santos', 'edwin.s@email.com', 4, 'Really good lunch set. Pizza, soup, and a drink for under 200 pesos. Can''t beat that value!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Felicity Cruz', 'felicity.c@email.com', 5, 'The anchovy pizza is surprisingly delicious! Salty, savory, and pairs perfectly with their white wine.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Gordon Reyes', 'gordon.r@email.com', 5, 'Pizza Volante is our family tradition every Sunday dinner. The kids are always excited. Food never disappoints!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Helena Mendoza', 'helena.m@email.com', 4, 'The new app for ordering is really smooth. Plus the reward points system is generous. Tech-forward pizza place!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Ivan Garcia', 'ivan.g@email.com', 5, 'Hands down the best pizza sauce in the city. Tangy, sweet, with a hint of herbs. Perfection.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Jasmine Bautista', 'jasmine.b@email.com', 4, 'Love their salad options. The Caesar salad is fresh and the dressing is house-made. Great healthy choice!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Kenneth Fernandez', 'kenneth.f@email.com', 5, 'My midnight snack spot! Love that they''re open late. The pepperoni and mushroom combo at 11pm hits different.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Lorna Lim', 'lorna.l@email.com', 5, 'The mozzarella sticks here are the crunchiest I''ve ever had! Perfect appetizer before the main pizza event.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Mario Aquino', 'mario.a@email.com', 4, 'Solid pizza, friendly crew, clean place. Everything you want from a neighborhood pizza joint. Keep it up!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Nadia Villanueva', 'nadia.v@email.com', 5, 'The bruschetta appetizer is chef-level quality! Perfectly toasted bread with fresh tomatoes and basil.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Oscar Dela Cruz', 'oscar.dc@email.com', 4, 'Great place to catch up with old friends over good pizza. Relaxed atmosphere and the food hits the spot.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Pauline Tan', 'pauline.t@email.com', 5, 'The pizza Volante special with sausage, peppers, and olives is an explosion of flavors! A must-order!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Quincy Gomez', 'quincy.g@email.com', 5, 'I''m dairy-free and they accommodate me so well! The vegan cheese option is actually good, not like cardboard.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Rita Ramos', 'rita.r@email.com', 4, 'The weekend all-you-can-eat pizza buffet is such a great deal! The selection keeps rotating too.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Samuel Navarro', 'samuel.n@email.com', 5, 'Every pizza is made to order! You can watch them prepare it through the glass. Fresh and made with care.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Tessa Ocampo', 'tessa.o@email.com', 4, 'The espresso here is surprisingly good for a pizza place. Nice to have a proper coffee after the meal.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Umberto Castillo', 'umberto.c@email.com', 5, 'First time trying the calzone and it was stuffed to the brim! Ham, cheese, mushrooms, and peppers. Incredible value!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Vera Flores', 'vera.f@email.com', 5, 'They remembered my daughter''s allergy from last visit without me reminding them. That''s exceptional service!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Warren Dizon', 'warren.d@email.com', 4, 'The herb-infused olive oil for dipping is a nice touch. Shows they care about the little details.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Xena Soriano', 'xena.s@email.com', 5, 'Best birthday party venue for kids! The staff organized games and the pizza party package was amazing.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Yuri Evangelista', 'yuri.e@email.com', 4, 'The roasted garlic pizza is so aromatic. You can smell it from across the restaurant. Tastes even better!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Zara Padilla', 'zara.p@email.com', 5, 'Pizza Volante is the only place that gets thin crust right. Crispy without being cracker-like. Perfection!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Adrian Manalo', 'adrian.m@email.com', 5, 'Just discovered their secret menu! The sriracha honey pizza is insanely good. Sweet, spicy, cheesy heaven!', 'positive', true, now() - interval '1 day' * floor(random() * 120)),
('Bernice Gutierrez', 'bernice.g@email.com', 4, 'Great outdoor patio seating. Enjoying pizza al fresco on a cool evening is the best feeling.', 'positive', true, now() - interval '1 day' * floor(random() * 120)),

-- Neutral reviews 421-450
('Clarence Salazar', 'clarence.s@email.com', 3, 'Standard pizza experience. I''ve had better but also had much worse. It''s middle of the road.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Daisy Aguilar', 'daisy.a@email.com', 3, 'The pasta was average. Not particularly memorable. Just a normal Italian chain restaurant feel.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Ernesto Chua', 'ernesto.c@email.com', 3, 'Okay pizza. The crust was a bit too thick and chewy for my taste but the sauce was decent.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Flora Del Rosario', 'flora.dr@email.com', 3, 'Had the supreme pizza. It was fine. Not as loaded as the menu picture suggested but still an okay meal.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Gilbert Morales', 'gilbert.m@email.com', 3, 'Normal pizza delivery. Took about 35 minutes. Pizza was warm and tasted standard. No complaints but no praise either.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Hazel Bernal', 'hazel.b@email.com', 3, 'The chicken wings were okay. Crispy enough but the sauce was too mild for my liking. Average.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Ismael Javier', 'ismael.j@email.com', 3, 'Went here because the other place was full. Pizza was acceptable. Nothing wrong, nothing exciting.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Janet Santiago', 'janet.s@email.com', 3, 'The menu has lots of options but everything tastes about the same to me. Average Italian food.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Karl Pascual', 'karl.p@email.com', 3, 'Pizza arrived on time. Was warm. Had cheese and toppings. It was pizza. That''s about all I can say.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Lydia Velasco', 'lydia.v@email.com', 3, 'The ambiance is nice but the food doesn''t match the setting. Pizza was just okay. Expected more.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Marcelo Gonzales', 'marcelo.g@email.com', 3, 'I''ve eaten here many times. It''s consistently average. Not bad enough to stop going but not good enough to rave about.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Nancy Dela Pena', 'nancy.dp@email.com', 3, 'The drink prices are a bit high for what you get. Food was standard. Just a regular meal out.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Orlando Hernandez', 'orlando.h@email.com', 3, 'Ordered the meat lovers. It had meat. It was on pizza. It was fine. Nothing more to add.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Priscilla Fuentes', 'priscilla.f@email.com', 3, 'The new menu items are interesting but the execution is just average. Good ideas, mediocre results.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),
('Reynaldo Roque', 'reynaldo.r@email.com', 3, 'Pizza was okay. A bit more cheese would have been nice. Service was neither fast nor slow. Just normal.', 'neutral', true, now() - interval '1 day' * floor(random() * 120)),

-- Negative reviews 451-500
('Sylvia Luna', 'sylvia.l@email.com', 2, 'Very noisy restaurant. Could barely hear my friend across the table. Food was mediocre at best.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Tomas Villareal', 'tomas.v@email.com', 1, 'The worst calzone I''ve ever had. It was basically bread with a tiny amount of filling. Felt scammed.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Ursula Ramirez', 'ursula.r@email.com', 2, 'The sauce tasted bitter and off. Like they used expired tomatoes. Could not finish my pizza.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Virgilio Martinez', 'virgilio.m@email.com', 1, 'Rude cashier rolled her eyes when I asked about allergens. Unacceptable attitude. Won''t risk my health here.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Wanda Fernandez', 'wanda.f@email.com', 2, 'The small pizza is laughably small. Like personal pan size but charged as a regular small. Not worth it.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Xerxes Ortiz', 'xerxes.o@email.com', 1, 'Found an eggshell in my pasta. Kitchen staff needs proper training. This is a food safety issue.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Yesenia Santos', 'yesenia.s@email.com', 2, 'The music was so loud I got a headache. Staff refused to turn it down. Pizza was below average too.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Zeke Cruz', 'zeke.c@email.com', 1, 'Delivery was 90 minutes late with no communication. When I called, they hung up on me. Worst service ever.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Abigail Torres', 'abigail.t@email.com', 2, 'The vegetable pizza had like three pieces of vegetable on it. More like a cheese pizza with garnish. Disappointing.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Bruno Reyes', 'bruno.r@email.com', 1, 'The pizza smelled old when I opened the box. Tasted stale too. Clearly not freshly made. Disgusting.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Catalina Mendoza', 'catalina.m@email.com', 2, 'The chairs are uncomfortable and the tables wobble. Hard to enjoy food when you can''t sit properly.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Dante Garcia', 'dante.g@email.com', 1, 'My order was completely wrong. Instead of pepperoni, I got anchovies. I hate anchovies. And they wouldn''t replace it.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Elsa Bautista', 'elsa.b@email.com', 2, 'The garlic bread was burnt and the pasta was cold. Seems like the kitchen was overwhelmed. Poor experience.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Faustino Fernandez', 'faustino.f@email.com', 1, 'I specifically asked for extra cheese but got less cheese than normal. Then they wanted to charge me for a remake. Unbelievable.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Graciela Lim', 'graciela.l@email.com', 2, 'The pizza box was crushed when it arrived. Pizza was smashed and cold. Driver didn''t seem to care at all.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Horacio Aquino', 'horacio.a@email.com', 1, 'Waited 15 minutes at the counter before anyone acknowledged us. Staff was chatting among themselves. Terrible management.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Imelda Villanueva', 'imelda.v@email.com', 2, 'The soup of the day tasted like hot water with food coloring. No flavor whatsoever. The breadsticks were hard.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Julio Dela Cruz', 'julio.dc@email.com', 1, 'There were ants on the table and the sugar dispenser. Health hazard! Will be filing a complaint.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Katarina Tan', 'katarina.t@email.com', 2, 'The dessert pizza was basically regular pizza with chocolate drizzled on it. Lazy and unappetizing.', 'negative', true, now() - interval '1 day' * floor(random() * 120)),
('Leonardo Gomez', 'leonardo.g@email.com', 1, 'My credit card was charged twice and it took 3 weeks and multiple calls to get a refund. Terrible business practices.', 'negative', true, now() - interval '1 day' * floor(random() * 120));
