
INSERT INTO public.reviews (name, email, rating, feedback, sentiment, approved, created_at) VALUES
-- Positive reviews 251-300
('Ariana Santos', 'ariana.s@email.com', 5, 'My go-to comfort food place! The cheese pizza here is like a warm hug. Perfect every single time.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Benedict Torres', 'benedict.t@email.com', 4, 'Really enjoyed the new spicy pepperoni. Has a nice kick without being overwhelming. Great addition to the menu!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Clarissa Reyes', 'clarissa.r@email.com', 5, 'The pesto pizza is divine! Fresh basil pesto, mozzarella, and cherry tomatoes. A masterpiece.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Dominic Cruz', 'dominic.c@email.com', 4, 'Brought my foreign colleagues here and they were impressed. Said it''s comparable to pizza in Italy!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Eleanor Mendoza', 'eleanor.m@email.com', 5, 'The dessert menu is underrated! The chocolate lava cake paired with their espresso is perfect.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Franco Garcia', 'franco.g@email.com', 5, 'Just had the new seafood pizza and WOW. Fresh shrimp, calamari, and a light garlic cream sauce. Outstanding!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Giselle Bautista', 'giselle.b@email.com', 4, 'Love the WiFi speed here lol. But seriously the pizza is great too. Perfect study spot with good food.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Harold Fernandez', 'harold.f@email.com', 5, 'The loyalty card rewards are generous! Got a free pizza after just 8 purchases. And the pizza is always fire.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Ingrid Lim', 'ingrid.l@email.com', 5, 'My pregnant cravings are always satisfied here! The extra cheese deep dish with olives hits different.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Jerome Aquino', 'jerome.a@email.com', 4, 'Good vibes, good food. The outdoor seating area is nice especially in the evenings. Pizza was delish!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Karen Villanueva', 'karen.v@email.com', 5, 'The catering service is top-notch! They handled our 50-person corporate lunch flawlessly.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Lorenzo Dela Cruz', 'lorenzo.dc@email.com', 4, 'The garlic knots as appetizers are absolutely addictive. Buttery, garlicky, and so soft inside.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Maricela Tan', 'maricela.t@email.com', 5, 'Everything tastes homemade here! The sauce, the dough, even the desserts. You can taste the love in every bite.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Nestor Gomez', 'nestor.g@email.com', 5, 'The chicken parm sandwich is incredible! Crispy chicken, melted cheese, marinara on a toasted sub. Perfection!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Olivia Ramos', 'olivia.r@email.com', 4, 'Consistent quality across multiple visits. That''s what keeps me coming back. The all-meat pizza is my fave.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Peter Navarro', 'peter.n@email.com', 5, 'Celebrated New Year''s here with friends. The party package was amazing value and the food was spectacular!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Queenie Ocampo', 'queenie.o@email.com', 4, 'The ranch dipping sauce with their pizza is *chef''s kiss*. Never thought I''d be a ranch-on-pizza person but here I am.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Rafael Castillo', 'rafael.c@email.com', 5, 'Late night pizza cravings? Pizza Volante delivers until midnight! And the quality at 11pm is the same as at lunch.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Stella Flores', 'stella.f@email.com', 5, 'The white pizza with ricotta and spinach is my healthy indulgence. So creamy and satisfying!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Theodore Dizon', 'theodore.d@email.com', 4, 'Great selection of craft beers to pair with pizza. The server recommended the perfect pairing. Impressive!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Uma Soriano', 'uma.s@email.com', 5, 'Every time I bring someone new here, they become a regular. That says everything about the quality!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Victor Evangelista', 'victor.e@email.com', 4, 'The bacon cheeseburger pizza is genius! All my favorite flavors on a pizza. Creative and delicious.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Wendy Padilla', 'wendy.p@email.com', 5, 'I''m a regular and the staff always greets me by name. Makes me feel like family. And the food? Always 10/10.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Xavier Manalo', 'xavier.m@email.com', 5, 'The quality of cheese they use is clearly premium. You can taste the difference. Worth every cent.', 'positive', true, now() - interval '1 day' * floor(random() * 90)),
('Yvonne Gutierrez', 'yvonne.g@email.com', 4, 'Nice kids play area that keeps the little ones entertained while we eat in peace. Smart move, Pizza Volante!', 'positive', true, now() - interval '1 day' * floor(random() * 90)),

-- Neutral reviews 301-335
('Zachary Salazar', 'zachary.s@email.com', 3, 'It was alright. Pizza had good cheese but the crust needed more flavor. Service was standard.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Alice Aguilar', 'alice.a@email.com', 3, 'Nothing wrong with the food but nothing spectacular either. Just a regular pizza dinner out.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Bernard Chua', 'bernard.c@email.com', 3, 'Average taste, average price, average experience. It fills you up but doesn''t excite your taste buds.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Cecilia Del Rosario', 'cecilia.dr@email.com', 3, 'The pizza was served warm, not hot. Tasted okay but I prefer it fresh from the oven. Decent overall.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Dario Morales', 'dario.m@email.com', 3, 'Went for takeout. Everything was packed fine. Pizza was okay. Just a normal takeout experience.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Estella Bernal', 'estella.b@email.com', 3, 'The garlic bread was good but the main pizza was just meh. Could use more seasoning in the sauce.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Fabian Javier', 'fabian.j@email.com', 3, 'Ordered the pasta special. It was filling but lacked depth of flavor. Wouldn''t say it''s bad, just mediocre.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Gladys Santiago', 'gladys.s@email.com', 3, 'The restaurant decor is dated but clean. Food was acceptable. Average neighborhood pizza joint.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Hugo Pascual', 'hugo.p@email.com', 3, 'Pizza was fine. Not as good as I remembered from last time. Maybe they changed something? Or maybe my expectations were just higher.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Irene Velasco', 'irene.v@email.com', 3, 'The iced tea was good. The pizza was standard. Nothing to write a review about but here I am.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Julian Gonzales', 'julian.g@email.com', 3, 'Adequate food for the price. The portions are normal sized. It''s a perfectly average pizza place.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Katrina Dela Pena', 'katrina.dp@email.com', 3, 'The seafood pasta was okay. Shrimp was cooked well but the sauce was too thin. Not bad, not great.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Leonardo Hernandez', 'leonardo.h@email.com', 3, 'Typical pizza chain quality. If you know what to expect, you won''t be disappointed. But you won''t be wowed either.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Martha Fuentes', 'martha.f@email.com', 3, 'Had lunch here on a Tuesday. Quiet atmosphere, quick service, standard pizza. A normal lunch.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),
('Norman Roque', 'norman.r@email.com', 3, 'The pepperoni pizza was fine. Could have used more pepperoni. Crust was nice though. Average overall.', 'neutral', true, now() - interval '1 day' * floor(random() * 90)),

-- Negative reviews 336-370
('Ophelia Luna', 'ophelia.l@email.com', 2, 'Very disappointing pasta. Overcooked noodles and the sauce was too salty. Not what I expected at all.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Pablo Villareal', 'pablo.v@email.com', 1, 'The worst delivery experience ever. Wrong order, cold food, and the delivery app showed 15 min but took 55 min.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Rosalinda Ramirez', 'rosalinda.r@email.com', 2, 'The pizza was dripping with oil. I literally had to pat it down with napkins. So greasy and unhealthy.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Salvador Martinez', 'salvador.m@email.com', 1, 'Staff argued with each other in front of customers. Very unprofessional. The food was also subpar.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Teodora Fernandez', 'teodora.f@email.com', 2, 'The AC was barely working and the place was packed. Uncomfortable dining experience. Pizza was lukewarm.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Ulysses Ortiz', 'ulysses.o@email.com', 1, 'Ordered a large pizza and it looked more like a medium. Either they shrunk their sizes or they''re scamming customers.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Valentina Santos', 'valentina.s@email.com', 2, 'The garlic bread was hard as a rock. Could barely bite into it. And the dipping sauce was cold and congealed.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('William Cruz', 'william.c@email.com', 1, 'No parking available and the street was full. When we finally got inside after 20 minutes, the wait for food was another 40 minutes. Ridiculous.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Ximena Torres', 'ximena.t@email.com', 2, 'The cheese was barely there. Like they sprinkled it on. For a pizza place, you''d think cheese would be a priority.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Yolanda Reyes', 'yolanda.r@email.com', 1, 'My pizza had toppings only on half of it. The other half was just sauce and crust. Quality control is non-existent.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Zenaida Mendoza', 'zenaida.m@email.com', 2, 'The fried chicken was reheated. You could tell because it was dry on the outside and lukewarm inside. Disappointing.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Alberto Garcia', 'alberto.g2@email.com', 1, 'Flies everywhere in the dining area. How is this place passing health inspections? Unbelievable.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Belen Bautista', 'belen.b@email.com', 2, 'The crust was so thick it was like eating bread with a hint of pizza flavoring. Way too doughy.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Cesar Fernandez', 'cesar.f2@email.com', 1, 'They forgot our drinks, brought the wrong dessert, and the pizza was cold. A disaster from start to finish.', 'negative', true, now() - interval '1 day' * floor(random() * 90)),
('Dolly Lim', 'dolly.l@email.com', 2, 'The online photos look nothing like the actual food. False advertising at its finest. Very misleading.', 'negative', true, now() - interval '1 day' * floor(random() * 90));
